name: Build and run traversal
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up C++ environment
      run: |
        sudo apt update
        sudo apt install -y g++ gdb make cmake curl libcurl4-openssl-dev
    - name: Install dependencies
      run: |
        sudo apt install -y libcurlpp-dev nlohmann-json3-dev
    - name: Compile
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
    - name: Test
      shell: bash
      env:
        WIKITOKEN: ${{ secrets.WIKITOKEN }}
      run: |
        cd build
        ctest
    - name: Run traversal
      shell: bash
      env:
        WIKITOKEN: ${{ secrets.WIKITOKEN }}
      run: |
        ./build/traversal
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
      with:
        limit-access-to-actor: true
